interface Expense {
    id: string;
    amount: number;
    note: string | null;
    expense_date: string;
    created_at: string;
  }
  
  export function exportToCSV(expenses: Expense[], month: string, year: number) {
    // CSV Headers
    const headers = ['Date', 'Amount (₹)', 'Note', 'Created At'];
    
    // CSV Rows
    const rows = expenses.map(expense => {
      const date = new Date(expense.expense_date).toLocaleDateString('en-IN');
      const amount = Number(expense.amount).toFixed(2);
      const note = expense.note || 'No note';
      const createdAt = new Date(expense.created_at).toLocaleDateString('en-IN');
      
      return [date, amount, `"${note}"`, createdAt];
    });
  
    // Calculate total
    const total = expenses.reduce((sum, exp) => sum + Number(exp.amount), 0).toFixed(2);
    
    // Add summary rows
    rows.push([]);
    rows.push(['Total', total, '', '']);
    rows.push(['Month', month, '', '']);
    rows.push(['Year', year.toString(), '', '']);
    rows.push(['Export Date', new Date().toLocaleDateString('en-IN'), '', '']);
  
    // Combine headers and rows
    const csvContent = [
      headers.join(','),
      ...rows.map(row => row.join(','))
    ].join('\n');
  
    // Create and download file
    const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
    const link = document.createElement('a');
    const url = URL.createObjectURL(blob);
    
    link.setAttribute('href', url);
    link.setAttribute('download', `expenses_${month}_${year}.csv`);
    link.style.visibility = 'hidden';
    
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  }
  
  export function exportToJSON(expenses: Expense[], month: string, year: number) {
    const total = expenses.reduce((sum, exp) => sum + Number(exp.amount), 0);
    
    const exportData = {
      month,
      year,
      exportDate: new Date().toISOString(),
      summary: {
        totalExpenses: expenses.length,
        totalAmount: total,
        currency: 'INR'
      },
      expenses: expenses.map(exp => ({
        date: exp.expense_date,
        amount: Number(exp.amount),
        note: exp.note || null,
        createdAt: exp.created_at
      }))
    };
  
    const jsonContent = JSON.stringify(exportData, null, 2);
    const blob = new Blob([jsonContent], { type: 'application/json' });
    const link = document.createElement('a');
    const url = URL.createObjectURL(blob);
    
    link.setAttribute('href', url);
    link.setAttribute('download', `expenses_${month}_${year}.json`);
    link.style.visibility = 'hidden';
    
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  }
  
  export function shareExpenses(expenses: Expense[], month: string, year: number) {
    const total = expenses.reduce((sum, exp) => sum + Number(exp.amount), 0);
    
    const text = `
  📊 Expense Report - ${month} ${year}
  
  Total Expenses: ${expenses.length}
  Total Amount: ₹${total.toFixed(2)}
  
  Recent Expenses:
  ${expenses.slice(0, 5).map(exp => 
    `• ${new Date(exp.expense_date).toLocaleDateString('en-IN')}: ₹${Number(exp.amount).toFixed(2)}${exp.note ? ` - ${exp.note}` : ''}`
  ).join('\n')}
  
  Generated by Expense Tracker
    `.trim();
  
    if (navigator.share) {
      navigator.share({
        title: `Expenses - ${month} ${year}`,
        text: text
      }).catch(() => {
        // Fallback: Copy to clipboard
        copyToClipboard(text);
      });
    } else {
      copyToClipboard(text);
    }
  }
  
  function copyToClipboard(text: string) {
    if (navigator.clipboard) {
      navigator.clipboard.writeText(text).then(() => {
        alert('Expense summary copied to clipboard!');
      });
    } else {
      // Fallback for older browsers
      const textArea = document.createElement('textarea');
      textArea.value = text;
      textArea.style.position = 'fixed';
      textArea.style.left = '-999999px';
      document.body.appendChild(textArea);
      textArea.select();
      try {
        document.execCommand('copy');
        alert('Expense summary copied to clipboard!');
      } catch (err) {
        alert('Failed to copy. Please try again.');
      }
      document.body.removeChild(textArea);
    }
  }